version: "3"

services:
  janus:
    image: canyan/janus-gateway:latest
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    volumes:
      - ./config/janus:/usr/local/etc/janus
      - ./local/janus-logs/janus.log:/var/log/janus.log
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/janus/info"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
