version: "3"

services:
  janus:
    image: canyan/janus-gateway:latest
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    volumes:
      - ./config/janus:/usr/local/etc/janus
      - ./local/janus-logs/janus.log:/var/log/janus.log
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/janus/info"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
